package br.com.vindiesel.view;

import br.com.vindiesel.control.TelaEntregaControl;
import br.com.vindiesel.model.Encomenda;
import br.com.vindiesel.model.Remetente;
import br.com.vindiesel.uteis.InterfaceJanela;
import java.awt.event.KeyEvent;
import javax.swing.ButtonGroup;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author william.mauro
 */
public class TelaEntrega extends javax.swing.JInternalFrame {

    TelaEntregaControl entregaControl;

    /**
     * Creates new form TelaVenda
     */
    public TelaEntrega() {
        initComponents();
    }

    public TelaEntrega(TelaEntregaControl control) {
        initComponents();
        entregaControl = control;
        InterfaceJanela.centralizarInternalFrame(this);
        InterfaceJanela.alteraIconePrincipaldoJInternalFrame(this, "br/com/vindiesel/img/delivery_truck_16x16.png");
        ButtonGroup bg = new ButtonGroup();
        bg.add(checkCnpj);
        bg.add(checkCpf);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tpEntrega = new javax.swing.JTabbedPane();
        panelListarEntrega = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEntrega = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        lblFreteFiltrado = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblFreteTotal = new javax.swing.JLabel();
        btLimparCamposTabEntrega = new javax.swing.JButton();
        btLimparCamposTabEntrega1 = new javax.swing.JButton();
        tfPesquisarEntrega = new javax.swing.JTextField();
        brBuscarEntrega = new javax.swing.JButton();
        btEditarEntrega = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        panelEditarEntrega = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cbTipoTramite = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        btAdicionarTramite = new javax.swing.JButton();
        btRemoverTramite = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTramite = new javax.swing.JTable();
        tfNomeTramite = new javax.swing.JTextField();
        btLimparCamposTramite = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tfObservacaoTramite = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btLimparCamposTabEntrega2 = new javax.swing.JButton();
        panelEfetivarEntrega = new javax.swing.JPanel();
        cbEncomenda = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbRemetente = new javax.swing.JComboBox<>();
        btEfetivarEntrega = new javax.swing.JButton();
        btLimparEfetivarEntrega = new javax.swing.JButton();
        btPesquisaAvancadaEncomenda = new javax.swing.JButton();
        btPesquisaAvancadaRemetente = new javax.swing.JButton();
        tfNome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        tfCep = new javax.swing.JTextField();
        btPesquisarCep = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox<>();
        tfCidade = new javax.swing.JTextField();
        tfNumero = new javax.swing.JTextField();
        tfBairro = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tfRua = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tfComplemento = new javax.swing.JTextArea();
        btPesquisaAvancadaDestinatario = new javax.swing.JButton();
        tfCodigoPessoa = new javax.swing.JFormattedTextField();
        checkCnpj = new javax.swing.JCheckBox();
        checkCpf = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Gerenciar entregas de mercadoria");
        setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Entrega de Mercadoria");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tpEntrega.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tpEntrega.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tpEntrega.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tpEntregaMouseReleased(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabela de Entregas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 204, 204))); // NOI18N

        tblEntrega.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblEntrega);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Frete Filtrado:");

        lblFreteFiltrado.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblFreteFiltrado.setText("[FreteFiltrado]");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Frete Total:");

        lblFreteTotal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblFreteTotal.setText("[FreteTotal]");

        btLimparCamposTabEntrega.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btLimparCamposTabEntrega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vindiesel/img/clear_32x32.png"))); // NOI18N
        btLimparCamposTabEntrega.setText("LIMPAR");
        btLimparCamposTabEntrega.setBorder(null);
        btLimparCamposTabEntrega.setBorderPainted(false);
        btLimparCamposTabEntrega.setContentAreaFilled(false);
        btLimparCamposTabEntrega.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btLimparCamposTabEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparCamposTabEntregaActionPerformed(evt);
            }
        });

        btLimparCamposTabEntrega1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btLimparCamposTabEntrega1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vindiesel/img/atualizar_32x32.png"))); // NOI18N
        btLimparCamposTabEntrega1.setText("ATUALIZAR");
        btLimparCamposTabEntrega1.setBorder(null);
        btLimparCamposTabEntrega1.setBorderPainted(false);
        btLimparCamposTabEntrega1.setContentAreaFilled(false);
        btLimparCamposTabEntrega1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btLimparCamposTabEntrega1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparCamposTabEntrega1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFreteFiltrado)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFreteTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 352, Short.MAX_VALUE)
                .addComponent(btLimparCamposTabEntrega1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btLimparCamposTabEntrega)
                .addGap(30, 30, 30))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblFreteFiltrado)
                    .addComponent(jLabel10)
                    .addComponent(lblFreteTotal)
                    .addComponent(btLimparCamposTabEntrega)
                    .addComponent(btLimparCamposTabEntrega1))
                .addContainerGap())
        );

        tfPesquisarEntrega.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tfPesquisarEntrega.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tfPesquisarEntrega.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPesquisarEntregaKeyReleased(evt);
            }
        });

        brBuscarEntrega.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        brBuscarEntrega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vindiesel/img/lupa_32x32.png"))); // NOI18N
        brBuscarEntrega.setText("BUSCAR");
        brBuscarEntrega.setBorder(null);
        brBuscarEntrega.setBorderPainted(false);
        brBuscarEntrega.setContentAreaFilled(false);
        brBuscarEntrega.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btEditarEntrega.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btEditarEntrega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vindiesel/img/visualizar_32x32.png"))); // NOI18N
        btEditarEntrega.setText("EDITAR");
        btEditarEntrega.setBorder(null);
        btEditarEntrega.setBorderPainted(false);
        btEditarEntrega.setContentAreaFilled(false);
        btEditarEntrega.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btEditarEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarEntregaActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setText("BUSCAR:");

        javax.swing.GroupLayout panelListarEntregaLayout = new javax.swing.GroupLayout(panelListarEntrega);
        panelListarEntrega.setLayout(panelListarEntregaLayout);
        panelListarEntregaLayout.setHorizontalGroup(
            panelListarEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListarEntregaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPesquisarEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(brBuscarEntrega)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btEditarEntrega)
                .addGap(30, 30, 30))
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelListarEntregaLayout.setVerticalGroup(
            panelListarEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListarEntregaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelListarEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brBuscarEntrega)
                    .addComponent(tfPesquisarEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEditarEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tpEntrega.addTab("Listar Entregas", panelListarEntrega);

        cbTipoTramite.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cbTipoTramite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saiu de :", "Foi para :", "Chegou Em :" }));

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel25.setText("OBSERVAÇÃO:");

        btAdicionarTramite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vindiesel/img/add_32x32.png"))); // NOI18N
        btAdicionarTramite.setBorder(null);
        btAdicionarTramite.setBorderPainted(false);
        btAdicionarTramite.setContentAreaFilled(false);
        btAdicionarTramite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarTramiteActionPerformed(evt);
            }
        });

        btRemoverTramite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vindiesel/img/remover_32x32.png"))); // NOI18N
        btRemoverTramite.setBorder(null);
        btRemoverTramite.setBorderPainted(false);
        btRemoverTramite.setContentAreaFilled(false);
        btRemoverTramite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverTramiteActionPerformed(evt);
            }
        });

        tblTramite.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTramite);

        tfNomeTramite.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        btLimparCamposTramite.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btLimparCamposTramite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vindiesel/img/clear_32x32.png"))); // NOI18N
        btLimparCamposTramite.setText("LIMPAR");
        btLimparCamposTramite.setBorder(null);
        btLimparCamposTramite.setBorderPainted(false);
        btLimparCamposTramite.setContentAreaFilled(false);

        tfObservacaoTramite.setColumns(20);
        tfObservacaoTramite.setRows(5);
        jScrollPane4.setViewportView(tfObservacaoTramite);

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel26.setText("TRAMITE:");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setText("Tramites de Entrega");

        btLimparCamposTabEntrega2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btLimparCamposTabEntrega2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vindiesel/img/atualizar_32x32.png"))); // NOI18N
        btLimparCamposTabEntrega2.setText("ATUALIZAR");
        btLimparCamposTabEntrega2.setBorder(null);
        btLimparCamposTabEntrega2.setBorderPainted(false);
        btLimparCamposTabEntrega2.setContentAreaFilled(false);
        btLimparCamposTabEntrega2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btLimparCamposTabEntrega2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparCamposTabEntrega2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbTipoTramite, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNomeTramite)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE))
                        .addGap(43, 43, 43)
                        .addComponent(btAdicionarTramite)
                        .addGap(27, 27, 27)
                        .addComponent(btRemoverTramite)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btLimparCamposTabEntrega2)
                        .addGap(18, 18, 18)
                        .addComponent(btLimparCamposTramite)
                        .addGap(20, 20, 20))))
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipoTramite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNomeTramite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btAdicionarTramite)
                            .addComponent(btRemoverTramite)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addComponent(jLabel25))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimparCamposTramite)
                    .addComponent(btLimparCamposTabEntrega2))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelEditarEntregaLayout = new javax.swing.GroupLayout(panelEditarEntrega);
        panelEditarEntrega.setLayout(panelEditarEntregaLayout);
        panelEditarEntregaLayout.setHorizontalGroup(
            panelEditarEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelEditarEntregaLayout.setVerticalGroup(
            panelEditarEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditarEntregaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tpEntrega.addTab("Editar Tramites", panelEditarEntrega);

        cbEncomenda.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("ENCOMENDA:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("REMETENTE:");

        cbRemetente.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        btEfetivarEntrega.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btEfetivarEntrega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vindiesel/img/finalizar_32x32.png"))); // NOI18N
        btEfetivarEntrega.setText("EFETIVAR");
        btEfetivarEntrega.setBorder(null);
        btEfetivarEntrega.setBorderPainted(false);
        btEfetivarEntrega.setContentAreaFilled(false);
        btEfetivarEntrega.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btEfetivarEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEfetivarEntregaActionPerformed(evt);
            }
        });

        btLimparEfetivarEntrega.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btLimparEfetivarEntrega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vindiesel/img/clear_32x32.png"))); // NOI18N
        btLimparEfetivarEntrega.setText("LIMPAR");
        btLimparEfetivarEntrega.setBorder(null);
        btLimparEfetivarEntrega.setBorderPainted(false);
        btLimparEfetivarEntrega.setContentAreaFilled(false);
        btLimparEfetivarEntrega.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btLimparEfetivarEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparEfetivarEntregaActionPerformed(evt);
            }
        });

        btPesquisaAvancadaEncomenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vindiesel/img/pesquisa_avancada_24x24.png"))); // NOI18N
        btPesquisaAvancadaEncomenda.setToolTipText("Pesquise por Encomendas existentes");
        btPesquisaAvancadaEncomenda.setBorder(null);
        btPesquisaAvancadaEncomenda.setBorderPainted(false);
        btPesquisaAvancadaEncomenda.setContentAreaFilled(false);
        btPesquisaAvancadaEncomenda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btPesquisaAvancadaEncomenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisaAvancadaEncomendaActionPerformed(evt);
            }
        });

        btPesquisaAvancadaRemetente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vindiesel/img/pesquisa_avancada_24x24.png"))); // NOI18N
        btPesquisaAvancadaRemetente.setToolTipText("Pesquisa por Remetentes existentes...");
        btPesquisaAvancadaRemetente.setBorder(null);
        btPesquisaAvancadaRemetente.setBorderPainted(false);
        btPesquisaAvancadaRemetente.setContentAreaFilled(false);
        btPesquisaAvancadaRemetente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btPesquisaAvancadaRemetente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisaAvancadaRemetenteActionPerformed(evt);
            }
        });

        tfNome.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("NOME:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("CPF / CNPJ:");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereco do Destinatario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 204, 204))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setText("CEP");

        tfCep.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tfCep.setToolTipText("Busca automatica");
        tfCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfCepKeyPressed(evt);
            }
        });

        btPesquisarCep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vindiesel/img/localizacao_32x32.png"))); // NOI18N
        btPesquisarCep.setBorder(null);
        btPesquisarCep.setBorderPainted(false);
        btPesquisarCep.setContentAreaFilled(false);
        btPesquisarCep.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btPesquisarCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarCepActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("ESTADO:");

        cbEstado.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        tfCidade.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        tfNumero.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        tfBairro.setColumns(15);
        tfBairro.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setText("NUMERO:");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setText("RUA:");

        tfRua.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setText("COMPLEMENTO");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("CIDADE:");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setText("BAIRRO:");

        tfComplemento.setColumns(20);
        tfComplemento.setRows(5);
        jScrollPane3.setViewportView(tfComplemento);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfNumero)
                                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(tfCidade, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)))
                            .addComponent(tfRua))
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(tfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btPesquisarCep, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170)
                        .addComponent(jLabel15)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13))
                            .addComponent(btPesquisarCep))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel11)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btPesquisaAvancadaDestinatario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vindiesel/img/pesquisa_avancada_24x24.png"))); // NOI18N
        btPesquisaAvancadaDestinatario.setToolTipText("Pesquisar por Destinatário ja existente");
        btPesquisaAvancadaDestinatario.setBorder(null);
        btPesquisaAvancadaDestinatario.setBorderPainted(false);
        btPesquisaAvancadaDestinatario.setContentAreaFilled(false);
        btPesquisaAvancadaDestinatario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btPesquisaAvancadaDestinatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisaAvancadaDestinatarioActionPerformed(evt);
            }
        });

        tfCodigoPessoa.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tfCodigoPessoa.setPreferredSize(new java.awt.Dimension(47, 30));

        checkCnpj.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        checkCnpj.setText("CNPJ");
        checkCnpj.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        checkCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCnpjActionPerformed(evt);
            }
        });

        checkCpf.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        checkCpf.setText("CPF");
        checkCpf.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        checkCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCpfActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Efetivar Entrega");

        javax.swing.GroupLayout panelEfetivarEntregaLayout = new javax.swing.GroupLayout(panelEfetivarEntrega);
        panelEfetivarEntrega.setLayout(panelEfetivarEntregaLayout);
        panelEfetivarEntregaLayout.setHorizontalGroup(
            panelEfetivarEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEfetivarEntregaLayout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addGroup(panelEfetivarEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEfetivarEntregaLayout.createSequentialGroup()
                        .addGap(407, 407, 407)
                        .addComponent(btLimparEfetivarEntrega)
                        .addGap(18, 18, 18)
                        .addComponent(btEfetivarEntrega)
                        .addGap(13, 13, 13))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelEfetivarEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelEfetivarEntregaLayout.createSequentialGroup()
                            .addGroup(panelEfetivarEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addGroup(panelEfetivarEntregaLayout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(12, 12, 12)))
                            .addGroup(panelEfetivarEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelEfetivarEntregaLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(panelEfetivarEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cbRemetente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btPesquisaAvancadaRemetente))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelEfetivarEntregaLayout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(panelEfetivarEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addGroup(panelEfetivarEntregaLayout.createSequentialGroup()
                                            .addComponent(tfCodigoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btPesquisaAvancadaDestinatario)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(checkCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(checkCpf))))
                        .addGroup(panelEfetivarEntregaLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(cbEncomenda, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btPesquisaAvancadaEncomenda))))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        panelEfetivarEntregaLayout.setVerticalGroup(
            panelEfetivarEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEfetivarEntregaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(panelEfetivarEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEfetivarEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(checkCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(checkCpf))
                    .addComponent(btPesquisaAvancadaDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelEfetivarEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(tfCodigoPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEfetivarEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEfetivarEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEfetivarEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(btPesquisaAvancadaRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(panelEfetivarEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEfetivarEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbEncomenda)
                        .addComponent(jLabel2))
                    .addComponent(btPesquisaAvancadaEncomenda, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelEfetivarEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btEfetivarEntrega)
                    .addComponent(btLimparEfetivarEntrega))
                .addContainerGap())
        );

        tpEntrega.addTab("Efetivar Entrega", panelEfetivarEntrega);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tpEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(tpEntrega))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfCepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCepKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            entregaControl.buscarCepAction();
        }
        
    }//GEN-LAST:event_tfCepKeyPressed

    private void btPesquisarCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarCepActionPerformed
        // TODO add your handling code here:
        entregaControl.buscarCepAction();
    }//GEN-LAST:event_btPesquisarCepActionPerformed

    private void btLimparEfetivarEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparEfetivarEntregaActionPerformed
        // TODO add your handling code here:
        entregaControl.limparCamposTabEfetivarEntregaAction();
    }//GEN-LAST:event_btLimparEfetivarEntregaActionPerformed

    private void btEfetivarEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEfetivarEntregaActionPerformed
        // TODO add your handling code here:
        entregaControl.chamarDialogEntregaReceitaAction();
    }//GEN-LAST:event_btEfetivarEntregaActionPerformed

    private void btPesquisaAvancadaEncomendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisaAvancadaEncomendaActionPerformed
        entregaControl.chamarDialogPesquisaAvancadaEncomendaAction();
        // TODO add your handling code here:
    }//GEN-LAST:event_btPesquisaAvancadaEncomendaActionPerformed

    private void btEditarEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarEntregaActionPerformed
        // TODO add your handling code here:
        entregaControl.listarTramitesDeUmaEntregaAction();

    }//GEN-LAST:event_btEditarEntregaActionPerformed

    private void btAdicionarTramiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarTramiteActionPerformed
        // TODO add your handling code here:
        entregaControl.adicionarTramitesDeUmaEntregaAction();
    }//GEN-LAST:event_btAdicionarTramiteActionPerformed

    private void btRemoverTramiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverTramiteActionPerformed
        // TODO add your handling code here:
        entregaControl.removerTramitesDeUmaEntregaAction();
    }//GEN-LAST:event_btRemoverTramiteActionPerformed

    private void tpEntregaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tpEntregaMouseReleased
        // TODO add your handling code here:
        if (tpEntrega.getSelectedIndex() == 0 || tpEntrega.getSelectedIndex() == 2) {
            entregaControl.resetarEntregaETramitesAction();
        }


    }//GEN-LAST:event_tpEntregaMouseReleased

    private void btLimparCamposTabEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparCamposTabEntregaActionPerformed
        // TODO add your handling code here:
        entregaControl.limparCamposTabEntrega();

    }//GEN-LAST:event_btLimparCamposTabEntregaActionPerformed

    private void btPesquisaAvancadaRemetenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisaAvancadaRemetenteActionPerformed
        // TODO add your handling code here:
        entregaControl.chamarDialogPesquisaAvancadaRemetenteAction();
    }//GEN-LAST:event_btPesquisaAvancadaRemetenteActionPerformed

    private void btPesquisaAvancadaDestinatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisaAvancadaDestinatarioActionPerformed
        // TODO add your handling code here:
        entregaControl.chamarDialogPesquisaAvancadaDestinatarioAction();

    }//GEN-LAST:event_btPesquisaAvancadaDestinatarioActionPerformed

    private void checkCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCnpjActionPerformed
        // TODO add your handling code here:
        entregaControl.formataTfCodigoPessoaParaCNPJ();
        tfCodigoPessoa.requestFocus();
    }//GEN-LAST:event_checkCnpjActionPerformed

    private void checkCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCpfActionPerformed
        // TODO add your handling code here:
        entregaControl.formataTfCodigoPessoaParaCPF();
        tfCodigoPessoa.requestFocus();
    }//GEN-LAST:event_checkCpfActionPerformed

    private void btLimparCamposTabEntrega1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparCamposTabEntrega1ActionPerformed
        // TODO add your handling code here:
        entregaControl.atualizarTabelaEntregaAction();
    }//GEN-LAST:event_btLimparCamposTabEntrega1ActionPerformed

    private void tfPesquisarEntregaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPesquisarEntregaKeyReleased
        // TODO add your handling code here:
        entregaControl.pesquisarEntregasAction();
        
    }//GEN-LAST:event_tfPesquisarEntregaKeyReleased

    private void btLimparCamposTabEntrega2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparCamposTabEntrega2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btLimparCamposTabEntrega2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brBuscarEntrega;
    private javax.swing.JButton btAdicionarTramite;
    private javax.swing.JButton btEditarEntrega;
    private javax.swing.JButton btEfetivarEntrega;
    private javax.swing.JButton btLimparCamposTabEntrega;
    private javax.swing.JButton btLimparCamposTabEntrega1;
    private javax.swing.JButton btLimparCamposTabEntrega2;
    private javax.swing.JButton btLimparCamposTramite;
    private javax.swing.JButton btLimparEfetivarEntrega;
    private javax.swing.JButton btPesquisaAvancadaDestinatario;
    private javax.swing.JButton btPesquisaAvancadaEncomenda;
    private javax.swing.JButton btPesquisaAvancadaRemetente;
    private javax.swing.JButton btPesquisarCep;
    private javax.swing.JButton btRemoverTramite;
    private javax.swing.JComboBox<Encomenda> cbEncomenda;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<Remetente> cbRemetente;
    private javax.swing.JComboBox<String> cbTipoTramite;
    private javax.swing.JCheckBox checkCnpj;
    private javax.swing.JCheckBox checkCpf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblFreteFiltrado;
    private javax.swing.JLabel lblFreteTotal;
    private javax.swing.JPanel panelEditarEntrega;
    private javax.swing.JPanel panelEfetivarEntrega;
    private javax.swing.JPanel panelListarEntrega;
    private javax.swing.JTable tblEntrega;
    private javax.swing.JTable tblTramite;
    private javax.swing.JTextField tfBairro;
    private javax.swing.JTextField tfCep;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JFormattedTextField tfCodigoPessoa;
    private javax.swing.JTextArea tfComplemento;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfNomeTramite;
    private javax.swing.JTextField tfNumero;
    private javax.swing.JTextArea tfObservacaoTramite;
    private javax.swing.JTextField tfPesquisarEntrega;
    private javax.swing.JTextField tfRua;
    private javax.swing.JTabbedPane tpEntrega;
    // End of variables declaration//GEN-END:variables

    public JComboBox<String> getCbEstado() {
        return cbEstado;
    }

    public void setCbEstado(JComboBox<String> cbEstado) {
        this.cbEstado = cbEstado;
    }

    public JTextField getTfBairro() {
        return tfBairro;
    }

    public void setTfBairro(JTextField tfBairro) {
        this.tfBairro = tfBairro;
    }

    public JTextField getTfCep() {
        return tfCep;
    }

    public void setTfCep(JTextField tfCep) {
        this.tfCep = tfCep;
    }

    public JTextField getTfCidade() {
        return tfCidade;
    }

    public void setTfCidade(JTextField tfCidade) {
        this.tfCidade = tfCidade;
    }

    public JTextArea getTfComplemento() {
        return tfComplemento;
    }

    public void setTfComplemento(JTextArea tfComplemento) {
        this.tfComplemento = tfComplemento;
    }

    public JTextField getTfNumero() {
        return tfNumero;
    }

    public void setTfNumero(JTextField tfNumero) {
        this.tfNumero = tfNumero;
    }

    public JTextField getTfRua() {
        return tfRua;
    }

    public void setTfRua(JTextField tfRua) {
        this.tfRua = tfRua;
    }

    public JComboBox<Encomenda> getCbEncomenda() {
        return cbEncomenda;
    }

    public void setCbEncomenda(JComboBox<Encomenda> cbEncomenda) {
        this.cbEncomenda = cbEncomenda;
    }

    public JComboBox<Remetente> getCbRemetente() {
        return cbRemetente;
    }

    public void setCbRemetente(JComboBox<Remetente> cbRemetente) {
        this.cbRemetente = cbRemetente;
    }

    public JFormattedTextField getTfCodigoPessoa() {
        return tfCodigoPessoa;
    }

    public void setTfCodigoPessoa(JFormattedTextField tfCodigoPessoa) {
        this.tfCodigoPessoa = tfCodigoPessoa;
    }

    public JTextField getTfNome() {
        return tfNome;
    }

    public void setTfNome(JTextField tfNome) {
        this.tfNome = tfNome;
    }

    public JComboBox<String> getCbTipoTramite() {
        return cbTipoTramite;
    }

    public void setCbTipoTramite(JComboBox<String> cbTipoTramite) {
        this.cbTipoTramite = cbTipoTramite;
    }

    public JTable getTblTramite() {
        return tblTramite;
    }

    public void setTblTramite(JTable tblTramite) {
        this.tblTramite = tblTramite;
    }

    public JTextField getTfNomeTramite() {
        return tfNomeTramite;
    }

    public void setTfNomeTramite(JTextField tfNomeTramite) {
        this.tfNomeTramite = tfNomeTramite;
    }

    public JTable getTblEntrega() {
        return tblEntrega;
    }

    public void setTblEntrega(JTable tblEntrega) {
        this.tblEntrega = tblEntrega;
    }

    public JTextField getTfPesquisarEntrega() {
        return tfPesquisarEntrega;
    }

    public void setTfPesquisarEntrega(JTextField tfPesquisarEntrega) {
        this.tfPesquisarEntrega = tfPesquisarEntrega;
    }

    public JTabbedPane getTpEntrega() {
        return tpEntrega;
    }

    public void setTpEntrega(JTabbedPane tpEntrega) {
        this.tpEntrega = tpEntrega;
    }

    public JTextArea getTfObservacaoTramite() {
        return tfObservacaoTramite;
    }

    public void setTfObservacaoTramite(JTextArea tfObservacaoTramite) {
        this.tfObservacaoTramite = tfObservacaoTramite;
    }

    public JCheckBox getCheckCnpj() {
        return checkCnpj;
    }

    public void setCheckCnpj(JCheckBox checkCnpj) {
        this.checkCnpj = checkCnpj;
    }

    public JCheckBox getCheckCpf() {
        return checkCpf;
    }

    public void setCheckCpf(JCheckBox checkCpf) {
        this.checkCpf = checkCpf;
    }

    public JLabel getLblFreteFiltrado() {
        return lblFreteFiltrado;
    }

    public void setLblFreteFiltrado(JLabel lblFreteFiltrado) {
        this.lblFreteFiltrado = lblFreteFiltrado;
    }

    public JLabel getLblFreteTotal() {
        return lblFreteTotal;
    }

    public void setLblFreteTotal(JLabel lblFreteTotal) {
        this.lblFreteTotal = lblFreteTotal;
    }
    
    
    

    
}
